# Configuration file for data

# Year of start process data
start_year: 1999

# Year of end process data
end_year: 2024

# List of columns to drop
drop_cols:
  - Age
  - GS

drop_features:
  - ORB%
  - BLK
  - STL%
  - 2P%
  - 3PAr
  - FTr
  - STL
  - TS%
  - 3P
  - TOV%
  - TRB%
  - DBPM
  - 3PA
  - OWS
  - AST%
  - BPM
  - eFG%
  - TRB
  - WS/48
  - FT
  - DRB%
  - FT%
  - 3P%
  - BLK%
