# team_shortcuts.yaml

teams_short:
  ATL: Atlanta Hawks
  BOS: Boston Celtics
  BKN: Brooklyn Nets
  CHA: Charlotte Hornets
  CHI: Chicago Bulls
  CLE: Cleveland Cavaliers
  DAL: Dallas Mavericks
  DEN: Denver Nuggets
  DET: Detroit Pistons
  GSW: Golden State Warriors
  HOU: Houston Rockets
  IND: Indiana Pacers
  LAC: LA Clippers
  LAL: Los Angeles Lakers
  MEM: Memphis Grizzlies
  MIA: Miami Heat
  MIL: Milwaukee Bucks
  MIN: Minnesota Timberwolves
  NOP: New Orleans Pelicans
  NYK: New York Knicks
  OKC: Oklahoma City Thunder
  ORL: Orlando Magic
  PHI: Philadelphia 76ers
  PHX: Phoenix Suns
  POR: Portland Trail Blazers
  SAC: Sacramento Kings
  SAS: San Antonio Spurs
  TOR: Toronto Raptors
  UTA: Utah Jazz
  WAS: Washington Wizards
  SEA: Seattle SuperSonics
  VAN: Vancouver Grizzlies
  NOK: New Orleans/Oklahoma City Hornets
  NOH: New Orleans Hornets
  CHA: Charlotte Bobcats
  NJN: New Jersey Nets
teams_long:
  Atlanta Hawks: ATL
  Boston Celtics: BOS
  Brooklyn Nets: BKN
  Charlotte Hornets: CHA
  Chicago Bulls: CHI
  Cleveland Cavaliers: CLE
  Dallas Mavericks: DAL
  Denver Nuggets: DEN
  Detroit Pistons: DET
  Golden State Warriors: GSW
  Houston Rockets: HOU
  Indiana Pacers: IND
  LA Clippers: LAC
  Los Angeles Clippers: LAC
  Los Angeles Lakers: LAL
  Memphis Grizzlies: MEM
  Miami Heat: MIA
  Milwaukee Bucks: MIL
  Minnesota Timberwolves: MIN
  New Orleans Pelicans: NOP
  New York Knicks: NYK
  Oklahoma City Thunder: OKC
  Orlando Magic: ORL
  Philadelphia 76ers: PHI
  Phoenix Suns: PHX
  Portland Trail Blazers: POR
  Sacramento Kings: SAC
  San Antonio Spurs: SAS
  Toronto Raptors: TOR
  Utah Jazz: UTA
  Washington Wizards: WAS
  Seattle SuperSonics: SEA
  Vancouver Grizzlies: VAN
  New Orleans/Oklahoma City Hornets: NOK
  New Orleans Hornets: NOH
  Charlotte Bobcats: CHA
  New Jersey Nets: NJN